### ISSUE TITLE
How to create ribbon excel with xll sdk c/c++?

### ISSUE THREAD

**Issue by Mabel328** [xlladdins/xll24#1]
I searched in your project how to create ribbon for excel with xll sdk c/c++ but didn't find.
 do you have any way to create it?

**Comment by keithalewis** [comment]
@Mabel328 The Excel C SDK does not provide any functionality for creating ribbons.
I use VSTO for that. See https://github.com/xlladdins/xlladdin/ for a simple example.

**Comment by Mabel328** [comment]
I want write by c/c++
I have referred to this project (1), it creates a ribbon "Add-ins", but can't add new buttons to the ribbon

(1) https://github.com/lionel-git/TestXll

Xloil also has the ability to create ribbons, but adding libraries is very difficult, can you refer to their code guide and simplify code?

**Comment by keithalewis** [comment]
@Mabel328 The project you reference does not create ribbons. You can only add menu items to call macros. The C API still has vestiges for dialog boxes, but those are no longer supported for 64-bit Excel.
If you want to write C/C++ you will have to use the COM API to Excel.

**Comment by Mabel328** [comment]
It is not an easy task, i will look into it
Thank you
